!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoalBounce
    - !Item
      name: GoodGoalMultiBounce
      rotations: [0, 45]
    - !Item
      name: BadGoal
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
