!ArenaConfig
arenas:
  0: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
    - !Item
      name: GoodGoalMulti
      rotations: [0, 45]
    - !Item
      name: BadGoal
