!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
    - !Item
      name: DeathZone
    - !Item
      name: GoodGoalMultiBounce
      rotations: [0, 45]
    - !Item
      name: BadGoal
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
