!ArenaConfig
arenas:
  0: !Arena
    t: 1000
    items:
    - !Item
      name: GoodGoalBounce
      sizes:
      - !Vector3 {x: 1, y: 1, z: 1}
      positions:
        - !Vector3 {x: 1, y: 0, z: 35}
    - !Item
      name: DeathZone
      sizes:
        - !Vector3 {x: 2, y: 10, z: 30}
      positions:
        - !Vector3 {x: 20, y: 10, z: 20}
      rotations: [90]
    - !Item
      name: BadGoal
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
        - !RGB {r: 153, g: 153, b: 153}
      sizes:
        - !Vector3 {x: 5, y: 10, z: 5}
        - !Vector3 {x: 2, y: 3, z: 2}
      positions:
        - !Vector3 {x: 10, y: 0, z: 10}
        - !Vector3 {x: 10, y: 0, z: 26}
