!ArenaConfig
arenas:
  0: !Arena
    t: 2000
    items:
    - !Item
      name: GoodGoal
    - !Item
      name: GoodGoalMulti
      rotations: [0, 45]
    - !Item
      name: BadGoal
    - !Item
      name: Wall
      colors:
        - !RGB {r: 153, g: 153, b: 153}
